x-spark-common: &spark-common
  build:
    context: ./spark
  user: root

x-airflow-common: &airflow-common
  build:
    context: ./airflow
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    - AIRFLOW__CORE__FERNET_KEY=C-ztmS7cxBn4crBlqvOGOosrLAhO28mp8pD3ekKc7i4=
    - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./logs:/opt/airflow/logs
    - ./scripts:/opt/spark/scripts
    - ./xmls:/opt/spark/xmls
    - ./jars:/opt/spark/user-jars

networks:
  data_network:
    driver: bridge

volumes:
  postgres_data:
  hadoop_namenode:
  hadoop_datanode:
  kafka_1_data:
  kafka_2_data:
  kafka_3_data:

services:
  # ================= SPARK CLUSTER (Apache Official) =================
  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077"
    environment:
      - PYSPARK_PYTHON=/usr/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.10
    volumes:
      - ./xmls:/opt/spark/xmls
      - ./scripts:/opt/spark/scripts
      - ./jars:/opt/spark/user-jars
    networks:
      - data_network

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - PYSPARK_PYTHON=/usr/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.10
    depends_on:
      - spark-master
    volumes:
      - ./xmls:/opt/spark/xmls
      - ./scripts:/opt/spark/scripts
      - ./jars:/opt/spark/user-jars
    networks:
      - data_network

  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - PYSPARK_PYTHON=/usr/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.10
    depends_on:
      - spark-master
    volumes:
      - ./xmls:/opt/spark/xmls
      - ./scripts:/opt/spark/scripts
      - ./jars:/opt/spark/user-jars
    networks:
      - data_network

  spark-worker-3:
    <<: *spark-common
    container_name: spark-worker-3
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - PYSPARK_PYTHON=/usr/bin/python3.10
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.10
    depends_on:
      - spark-master
    volumes:
      - ./xmls:/opt/spark/xmls
      - ./scripts:/opt/spark/scripts
      - ./jars:/opt/spark/user-jars
    networks:
      - data_network

  # ================= KAFKA CLUSTER (Confluent Inc) =================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    user: root
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - data_network

  kafka-1:
    image: confluentinc/cp-kafka:7.5.0
    user: root
    container_name: kafka-1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - kafka_1_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "29092:29092"
    networks:
      - data_network
    command: >
      sh -c "rm -f /var/lib/kafka/data/meta.properties && /etc/confluent/docker/run"

  kafka-2:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka-2
    user: root
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - kafka_2_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "29093:29093"
    networks:
      - data_network
    command: >
      sh -c "rm -f /var/lib/kafka/data/meta.properties && /etc/confluent/docker/run"

  kafka-3:
    image: confluentinc/cp-kafka:7.5.0
    user: root
    container_name: kafka-3
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,EXTERNAL://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
    volumes:
      - kafka_3_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "29094:29094"
    networks:
      - data_network
    command: >
      sh -c "rm -f /var/lib/kafka/data/meta.properties && /etc/confluent/docker/run"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - data_network

  # ================= AIRFLOW =================
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db-metastore.sql:/docker-entrypoint-initdb.d/init-db-metastore.sql
    networks:
      - data_network

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    depends_on:
      - postgres
    command: >
      bash -c "airflow db init &&
      airflow users create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin"
    networks:
      - data_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    depends_on:
      - postgres
      - airflow-init
    command: webserver
    ports:
      - "8081:8080" # Avoid conflict with Spark Master
    networks:
      - data_network

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    depends_on:
      - postgres
      - airflow-init
    command: scheduler
    networks:
      - data_network

  # ================= HIVE 4.0.0 STACK =================
  namenode:
    image: apache/hadoop:3.4.0
    container_name: namenode
    hostname: namenode
    user: root
    #command: ["hdfs", "namenode"]
    command: >
      /bin/bash -c "
      if [ ! -f /opt/hadoop/data/name/current/VERSION ]; then
        echo 'Formatando NameNode pela primeira vez...';
        hdfs namenode -format -force;
      fi;
      hdfs namenode"
    environment:
      # Formato: CORE-SITE.XML_<propriedade>=valor → gera core-site.xml
      # Formato: HDFS-SITE.XML_<propriedade>=valor → gera hdfs-site.xml
      CORE-SITE.XML_fs.defaultFS: "hdfs://namenode:9000"
      HDFS-SITE.XML_dfs.namenode.name.dir: "/opt/hadoop/data/name"
      # Formata o Namenode automaticamente se o diretório estiver vazio
      ENSURE_NAMENODE_DIR: "/opt/hadoop/data/name"
      HDFS-SITE.XML_dfs.permissions.enabled: "false"
      HDFS-SITE.XML_dfs.namenode.http-address: "0.0.0.0:9870"
    volumes:
      - hadoop_namenode:/opt/hadoop/data/name
    ports:
      - "9870:9870"
      - "9000:9000"
    networks:
      - data_network

  datanode:
    image: apache/hadoop:3.4.0
    container_name: datanode
    hostname: datanode
    user: root
    command: ["hdfs", "datanode"]
    environment:
      CORE-SITE.XML_fs.defaultFS: "hdfs://namenode:9000"
      HDFS-SITE.XML_dfs.datanode.data.dir: "/opt/hadoop/data/data"
      HDFS-SITE.XML_dfs.permissions.enabled: "false"
    depends_on:
      - namenode
    volumes:
      - hadoop_datanode:/opt/hadoop/data/data
    networks:
      - data_network

  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
      namenode:
        condition: service_started
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: >
        -Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
        -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
        -Djavax.jdo.option.ConnectionUserName=hive
        -Djavax.jdo.option.ConnectionPassword=hive
        -Dhive.metastore.uris=thrift://hive-metastore:9083
        -Dhive.metastore.warehouse.dir=hdfs://namenode:9000/user/hive/warehouse
    volumes:
      # IMPORTANTE: Você precisa ter o driver do postgres na pasta ./jars
      - ./jars/postgresql-42.7.5.jar:/opt/hive/lib/postgres.jar:ro
    ports:
      - "9083:9083"
    networks:
      - data_network
    # O Hive 4 precisa inicializar o schema se o banco for novo
    command: >
      /bin/bash -c "/opt/hive/bin/schematool -dbType postgres -initSchema && /opt/hive/bin/hive --service metastore"

  hive-server:
    image: apache/hive:4.0.0
    container_name: hive-server
    depends_on:
      - hive-metastore
    environment:
      SERVICE_NAME: hiveserver2
      SERVICE_OPTS: >
        -Dhive.metastore.uris=thrift://hive-metastore:9083
        -Dhive.metastore.warehouse.dir=hdfs://namenode:9000/user/hive/warehouse
    ports:
      - "10000:10000"
      - "10002:10002" # HiveServer2 Web UI
    networks:
      - data_network
